# Generated by Django 5.0.1 on 2024-02-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_alter_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ticket',
        ),
    ]
