# Generated by Django 5.0.1 on 2024-02-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0007_review_description_review_title_alter_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='descriptionReview',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='imageReview',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='titleReview',
        ),
    ]
