# Generated by Django 5.0.1 on 2024-02-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0008_rename_description_review_descriptionreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptionReview',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='imageReview',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='titleReview',
            new_name='title',
        ),
    ]
