# Generated by Django 5.0.1 on 2024-02-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0010_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='djangoApp.ticket'),
        ),
    ]
